declare module "*.module.css";
declare module "*.module.scss";
declare module "*.module.sass";
declare module "*.svg";
declare module "*.png";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.pdf";
declare module 'react-credit-cards'
